# Site settings
title: Bergel Taekwon-Do ITF
author:
  name: Alexandre Bergel
  email: alexandre.bergel@me.com
description: "Site du club Bergel Taekwon-Do ITF"

# Build settings
remote_theme: jekyll/minima
